USE ras_subject_analysis;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE articles;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/articles.csv' INTO TABLE articles CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE authors;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/authors.csv' INTO TABLE authors CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE article_authors;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/article_authors.csv' INTO TABLE article_authors CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE author_article_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/author_article_stats.csv' INTO TABLE author_article_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE author_article_stats_by_time_window;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/author_article_stats_by_time_window.csv' INTO TABLE author_article_stats_by_time_window CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE author_article_details;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/author_article_details.csv' INTO TABLE author_article_details CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subjects;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subjects.csv' INTO TABLE subjects CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE article_subjects;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/article_subjects.csv' INTO TABLE article_subjects CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE time_windows;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/time_windows.csv' INTO TABLE time_windows CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_l1_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_l1_time_stats.csv' INTO TABLE subject_l1_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_l2_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_l2_time_stats.csv' INTO TABLE subject_l2_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_distribution_all_years;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_distribution_all_years.csv' INTO TABLE subject_distribution_all_years CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_distribution_time_window;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_distribution_time_window.csv' INTO TABLE subject_distribution_time_window CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_diversity_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_diversity_stats.csv' INTO TABLE subject_diversity_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE subject_network_centrality_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/subject_network_centrality_stats.csv' INTO TABLE subject_network_centrality_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE network_nodes;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/network_nodes.csv' INTO TABLE network_nodes CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE network_article_edges;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/network_article_edges.csv' INTO TABLE network_article_edges CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE network_time_edges;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/network_time_edges.csv' INTO TABLE network_time_edges CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_term_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_term_time_stats.csv' INTO TABLE title_term_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_bigram_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_bigram_time_stats.csv' INTO TABLE title_bigram_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_tfidf_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_tfidf_time_stats.csv' INTO TABLE title_tfidf_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_term_subject_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_term_subject_time_stats.csv' INTO TABLE title_term_subject_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE article_title_terms;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/article_title_terms.csv' INTO TABLE article_title_terms CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_place_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_place_time_stats.csv' INTO TABLE title_place_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_place_subject_time_stats;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_place_subject_time_stats.csv' INTO TABLE title_place_subject_time_stats CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE article_title_places;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/article_title_places.csv' INTO TABLE article_title_places CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
TRUNCATE TABLE title_place_name_mapping;
LOAD DATA LOCAL INFILE 'C:/ras_text_analysis/social_network_subject_correct/database_export/title_place_name_mapping.csv' INTO TABLE title_place_name_mapping CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS = 1;
